name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      OFFICIAL_BUILD: 'True'
      # Set the build number in MinVer.
      MINVERBUILDMETADATA: build.${{github.run_number}}
  
    steps:
    - uses: actions/checkout@v3

    - name: Check if I need GCC
      run: |
        gcc -v
    
    - name: Compile Errythang
      run: |
        g++ -o out -I ./*.cpp
        find . -type f -name "*.o"
    
    - name: Generate SBOM
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn Test -pv 1.0.1 -ps Elijah_Nunez -nsb http://workflowtest/ -v Verbose
        ls ./_manifest/spdx_2.2/
        cat ./_manifest/spdx_2.2/manifest.spdx.json
      #Build and upload Artifacts
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./_manifest